config = {
    "mqtt":{
        "broker_url":"139.224.128.15",
        "broker_port":1883,
        "connect_timeout_s":60
    },
    "mongo":{
        "server_url":"139.224.128.15",
        "server_port":27017
    },
    "cloud_ali":{
        "live":{
            "auth_url":"http://www.yangxudong.com:8085/cm_add_live_detect_notify",
            "auth_key":"yangxudong"
        },
        "vod":{
        },
        "oss":{
        }
    }
}
